// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/inspire-middleware/pkg/db/ent/appgoodscope"
	"github.com/NpoolPlatform/inspire-middleware/pkg/db/ent/predicate"
)

// AppGoodScopeQuery is the builder for querying AppGoodScope entities.
type AppGoodScopeQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AppGoodScope
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AppGoodScopeQuery builder.
func (agsq *AppGoodScopeQuery) Where(ps ...predicate.AppGoodScope) *AppGoodScopeQuery {
	agsq.predicates = append(agsq.predicates, ps...)
	return agsq
}

// Limit adds a limit step to the query.
func (agsq *AppGoodScopeQuery) Limit(limit int) *AppGoodScopeQuery {
	agsq.limit = &limit
	return agsq
}

// Offset adds an offset step to the query.
func (agsq *AppGoodScopeQuery) Offset(offset int) *AppGoodScopeQuery {
	agsq.offset = &offset
	return agsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (agsq *AppGoodScopeQuery) Unique(unique bool) *AppGoodScopeQuery {
	agsq.unique = &unique
	return agsq
}

// Order adds an order step to the query.
func (agsq *AppGoodScopeQuery) Order(o ...OrderFunc) *AppGoodScopeQuery {
	agsq.order = append(agsq.order, o...)
	return agsq
}

// First returns the first AppGoodScope entity from the query.
// Returns a *NotFoundError when no AppGoodScope was found.
func (agsq *AppGoodScopeQuery) First(ctx context.Context) (*AppGoodScope, error) {
	nodes, err := agsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{appgoodscope.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (agsq *AppGoodScopeQuery) FirstX(ctx context.Context) *AppGoodScope {
	node, err := agsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AppGoodScope ID from the query.
// Returns a *NotFoundError when no AppGoodScope ID was found.
func (agsq *AppGoodScopeQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = agsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{appgoodscope.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (agsq *AppGoodScopeQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := agsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AppGoodScope entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AppGoodScope entity is found.
// Returns a *NotFoundError when no AppGoodScope entities are found.
func (agsq *AppGoodScopeQuery) Only(ctx context.Context) (*AppGoodScope, error) {
	nodes, err := agsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{appgoodscope.Label}
	default:
		return nil, &NotSingularError{appgoodscope.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (agsq *AppGoodScopeQuery) OnlyX(ctx context.Context) *AppGoodScope {
	node, err := agsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AppGoodScope ID in the query.
// Returns a *NotSingularError when more than one AppGoodScope ID is found.
// Returns a *NotFoundError when no entities are found.
func (agsq *AppGoodScopeQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = agsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{appgoodscope.Label}
	default:
		err = &NotSingularError{appgoodscope.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (agsq *AppGoodScopeQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := agsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AppGoodScopes.
func (agsq *AppGoodScopeQuery) All(ctx context.Context) ([]*AppGoodScope, error) {
	if err := agsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return agsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (agsq *AppGoodScopeQuery) AllX(ctx context.Context) []*AppGoodScope {
	nodes, err := agsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AppGoodScope IDs.
func (agsq *AppGoodScopeQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := agsq.Select(appgoodscope.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (agsq *AppGoodScopeQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := agsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (agsq *AppGoodScopeQuery) Count(ctx context.Context) (int, error) {
	if err := agsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return agsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (agsq *AppGoodScopeQuery) CountX(ctx context.Context) int {
	count, err := agsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (agsq *AppGoodScopeQuery) Exist(ctx context.Context) (bool, error) {
	if err := agsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return agsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (agsq *AppGoodScopeQuery) ExistX(ctx context.Context) bool {
	exist, err := agsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AppGoodScopeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (agsq *AppGoodScopeQuery) Clone() *AppGoodScopeQuery {
	if agsq == nil {
		return nil
	}
	return &AppGoodScopeQuery{
		config:     agsq.config,
		limit:      agsq.limit,
		offset:     agsq.offset,
		order:      append([]OrderFunc{}, agsq.order...),
		predicates: append([]predicate.AppGoodScope{}, agsq.predicates...),
		// clone intermediate query.
		sql:    agsq.sql.Clone(),
		path:   agsq.path,
		unique: agsq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AppGoodScope.Query().
//		GroupBy(appgoodscope.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (agsq *AppGoodScopeQuery) GroupBy(field string, fields ...string) *AppGoodScopeGroupBy {
	grbuild := &AppGoodScopeGroupBy{config: agsq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := agsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return agsq.sqlQuery(ctx), nil
	}
	grbuild.label = appgoodscope.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.AppGoodScope.Query().
//		Select(appgoodscope.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (agsq *AppGoodScopeQuery) Select(fields ...string) *AppGoodScopeSelect {
	agsq.fields = append(agsq.fields, fields...)
	selbuild := &AppGoodScopeSelect{AppGoodScopeQuery: agsq}
	selbuild.label = appgoodscope.Label
	selbuild.flds, selbuild.scan = &agsq.fields, selbuild.Scan
	return selbuild
}

func (agsq *AppGoodScopeQuery) prepareQuery(ctx context.Context) error {
	for _, f := range agsq.fields {
		if !appgoodscope.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if agsq.path != nil {
		prev, err := agsq.path(ctx)
		if err != nil {
			return err
		}
		agsq.sql = prev
	}
	if appgoodscope.Policy == nil {
		return errors.New("ent: uninitialized appgoodscope.Policy (forgotten import ent/runtime?)")
	}
	if err := appgoodscope.Policy.EvalQuery(ctx, agsq); err != nil {
		return err
	}
	return nil
}

func (agsq *AppGoodScopeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AppGoodScope, error) {
	var (
		nodes = []*AppGoodScope{}
		_spec = agsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*AppGoodScope).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &AppGoodScope{config: agsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(agsq.modifiers) > 0 {
		_spec.Modifiers = agsq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, agsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (agsq *AppGoodScopeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := agsq.querySpec()
	if len(agsq.modifiers) > 0 {
		_spec.Modifiers = agsq.modifiers
	}
	_spec.Node.Columns = agsq.fields
	if len(agsq.fields) > 0 {
		_spec.Unique = agsq.unique != nil && *agsq.unique
	}
	return sqlgraph.CountNodes(ctx, agsq.driver, _spec)
}

func (agsq *AppGoodScopeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := agsq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (agsq *AppGoodScopeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appgoodscope.Table,
			Columns: appgoodscope.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: appgoodscope.FieldID,
			},
		},
		From:   agsq.sql,
		Unique: true,
	}
	if unique := agsq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := agsq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appgoodscope.FieldID)
		for i := range fields {
			if fields[i] != appgoodscope.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := agsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := agsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := agsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := agsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (agsq *AppGoodScopeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(agsq.driver.Dialect())
	t1 := builder.Table(appgoodscope.Table)
	columns := agsq.fields
	if len(columns) == 0 {
		columns = appgoodscope.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if agsq.sql != nil {
		selector = agsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if agsq.unique != nil && *agsq.unique {
		selector.Distinct()
	}
	for _, m := range agsq.modifiers {
		m(selector)
	}
	for _, p := range agsq.predicates {
		p(selector)
	}
	for _, p := range agsq.order {
		p(selector)
	}
	if offset := agsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := agsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (agsq *AppGoodScopeQuery) ForUpdate(opts ...sql.LockOption) *AppGoodScopeQuery {
	if agsq.driver.Dialect() == dialect.Postgres {
		agsq.Unique(false)
	}
	agsq.modifiers = append(agsq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return agsq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (agsq *AppGoodScopeQuery) ForShare(opts ...sql.LockOption) *AppGoodScopeQuery {
	if agsq.driver.Dialect() == dialect.Postgres {
		agsq.Unique(false)
	}
	agsq.modifiers = append(agsq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return agsq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (agsq *AppGoodScopeQuery) Modify(modifiers ...func(s *sql.Selector)) *AppGoodScopeSelect {
	agsq.modifiers = append(agsq.modifiers, modifiers...)
	return agsq.Select()
}

// AppGoodScopeGroupBy is the group-by builder for AppGoodScope entities.
type AppGoodScopeGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (agsgb *AppGoodScopeGroupBy) Aggregate(fns ...AggregateFunc) *AppGoodScopeGroupBy {
	agsgb.fns = append(agsgb.fns, fns...)
	return agsgb
}

// Scan applies the group-by query and scans the result into the given value.
func (agsgb *AppGoodScopeGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := agsgb.path(ctx)
	if err != nil {
		return err
	}
	agsgb.sql = query
	return agsgb.sqlScan(ctx, v)
}

func (agsgb *AppGoodScopeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range agsgb.fields {
		if !appgoodscope.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := agsgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := agsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (agsgb *AppGoodScopeGroupBy) sqlQuery() *sql.Selector {
	selector := agsgb.sql.Select()
	aggregation := make([]string, 0, len(agsgb.fns))
	for _, fn := range agsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(agsgb.fields)+len(agsgb.fns))
		for _, f := range agsgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(agsgb.fields...)...)
}

// AppGoodScopeSelect is the builder for selecting fields of AppGoodScope entities.
type AppGoodScopeSelect struct {
	*AppGoodScopeQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (agss *AppGoodScopeSelect) Scan(ctx context.Context, v interface{}) error {
	if err := agss.prepareQuery(ctx); err != nil {
		return err
	}
	agss.sql = agss.AppGoodScopeQuery.sqlQuery(ctx)
	return agss.sqlScan(ctx, v)
}

func (agss *AppGoodScopeSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := agss.sql.Query()
	if err := agss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (agss *AppGoodScopeSelect) Modify(modifiers ...func(s *sql.Selector)) *AppGoodScopeSelect {
	agss.modifiers = append(agss.modifiers, modifiers...)
	return agss
}
