// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/inspire-middleware/pkg/db/ent/coinallocated"
	"github.com/NpoolPlatform/inspire-middleware/pkg/db/ent/predicate"
)

// CoinAllocatedDelete is the builder for deleting a CoinAllocated entity.
type CoinAllocatedDelete struct {
	config
	hooks    []Hook
	mutation *CoinAllocatedMutation
}

// Where appends a list predicates to the CoinAllocatedDelete builder.
func (cad *CoinAllocatedDelete) Where(ps ...predicate.CoinAllocated) *CoinAllocatedDelete {
	cad.mutation.Where(ps...)
	return cad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cad *CoinAllocatedDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cad.hooks) == 0 {
		affected, err = cad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CoinAllocatedMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cad.mutation = mutation
			affected, err = cad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cad.hooks) - 1; i >= 0; i-- {
			if cad.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (cad *CoinAllocatedDelete) ExecX(ctx context.Context) int {
	n, err := cad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cad *CoinAllocatedDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: coinallocated.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: coinallocated.FieldID,
			},
		},
	}
	if ps := cad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// CoinAllocatedDeleteOne is the builder for deleting a single CoinAllocated entity.
type CoinAllocatedDeleteOne struct {
	cad *CoinAllocatedDelete
}

// Exec executes the deletion query.
func (cado *CoinAllocatedDeleteOne) Exec(ctx context.Context) error {
	n, err := cado.cad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{coinallocated.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cado *CoinAllocatedDeleteOne) ExecX(ctx context.Context) {
	cado.cad.ExecX(ctx)
}
