// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/inspire-middleware/pkg/db/ent/couponscope"
	"github.com/google/uuid"
)

// CouponScope is the model entity for the CouponScope schema.
type CouponScope struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt uint32 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt uint32 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt uint32 `json:"deleted_at,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID uuid.UUID `json:"app_id,omitempty"`
	// CouponID holds the value of the "coupon_id" field.
	CouponID uuid.UUID `json:"coupon_id,omitempty"`
	// AppGoodID holds the value of the "app_good_id" field.
	AppGoodID uuid.UUID `json:"app_good_id,omitempty"`
	// CouponScope holds the value of the "coupon_scope" field.
	CouponScope string `json:"coupon_scope,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CouponScope) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case couponscope.FieldCreatedAt, couponscope.FieldUpdatedAt, couponscope.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case couponscope.FieldCouponScope:
			values[i] = new(sql.NullString)
		case couponscope.FieldID, couponscope.FieldAppID, couponscope.FieldCouponID, couponscope.FieldAppGoodID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type CouponScope", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CouponScope fields.
func (cs *CouponScope) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case couponscope.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				cs.ID = *value
			}
		case couponscope.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				cs.CreatedAt = uint32(value.Int64)
			}
		case couponscope.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				cs.UpdatedAt = uint32(value.Int64)
			}
		case couponscope.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				cs.DeletedAt = uint32(value.Int64)
			}
		case couponscope.FieldAppID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value != nil {
				cs.AppID = *value
			}
		case couponscope.FieldCouponID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field coupon_id", values[i])
			} else if value != nil {
				cs.CouponID = *value
			}
		case couponscope.FieldAppGoodID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field app_good_id", values[i])
			} else if value != nil {
				cs.AppGoodID = *value
			}
		case couponscope.FieldCouponScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field coupon_scope", values[i])
			} else if value.Valid {
				cs.CouponScope = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this CouponScope.
// Note that you need to call CouponScope.Unwrap() before calling this method if this CouponScope
// was returned from a transaction, and the transaction was committed or rolled back.
func (cs *CouponScope) Update() *CouponScopeUpdateOne {
	return (&CouponScopeClient{config: cs.config}).UpdateOne(cs)
}

// Unwrap unwraps the CouponScope entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cs *CouponScope) Unwrap() *CouponScope {
	_tx, ok := cs.config.driver.(*txDriver)
	if !ok {
		panic("ent: CouponScope is not a transactional entity")
	}
	cs.config.driver = _tx.drv
	return cs
}

// String implements the fmt.Stringer.
func (cs *CouponScope) String() string {
	var builder strings.Builder
	builder.WriteString("CouponScope(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cs.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", cs.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", cs.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", cs.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(fmt.Sprintf("%v", cs.AppID))
	builder.WriteString(", ")
	builder.WriteString("coupon_id=")
	builder.WriteString(fmt.Sprintf("%v", cs.CouponID))
	builder.WriteString(", ")
	builder.WriteString("app_good_id=")
	builder.WriteString(fmt.Sprintf("%v", cs.AppGoodID))
	builder.WriteString(", ")
	builder.WriteString("coupon_scope=")
	builder.WriteString(cs.CouponScope)
	builder.WriteByte(')')
	return builder.String()
}

// CouponScopes is a parsable slice of CouponScope.
type CouponScopes []*CouponScope

func (cs CouponScopes) config(cfg config) {
	for _i := range cs {
		cs[_i].config = cfg
	}
}
