// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/inspire-middleware/pkg/db/ent/goodachievement"
	"github.com/NpoolPlatform/inspire-middleware/pkg/db/ent/predicate"
)

// GoodAchievementQuery is the builder for querying GoodAchievement entities.
type GoodAchievementQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.GoodAchievement
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GoodAchievementQuery builder.
func (gaq *GoodAchievementQuery) Where(ps ...predicate.GoodAchievement) *GoodAchievementQuery {
	gaq.predicates = append(gaq.predicates, ps...)
	return gaq
}

// Limit adds a limit step to the query.
func (gaq *GoodAchievementQuery) Limit(limit int) *GoodAchievementQuery {
	gaq.limit = &limit
	return gaq
}

// Offset adds an offset step to the query.
func (gaq *GoodAchievementQuery) Offset(offset int) *GoodAchievementQuery {
	gaq.offset = &offset
	return gaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gaq *GoodAchievementQuery) Unique(unique bool) *GoodAchievementQuery {
	gaq.unique = &unique
	return gaq
}

// Order adds an order step to the query.
func (gaq *GoodAchievementQuery) Order(o ...OrderFunc) *GoodAchievementQuery {
	gaq.order = append(gaq.order, o...)
	return gaq
}

// First returns the first GoodAchievement entity from the query.
// Returns a *NotFoundError when no GoodAchievement was found.
func (gaq *GoodAchievementQuery) First(ctx context.Context) (*GoodAchievement, error) {
	nodes, err := gaq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{goodachievement.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gaq *GoodAchievementQuery) FirstX(ctx context.Context) *GoodAchievement {
	node, err := gaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GoodAchievement ID from the query.
// Returns a *NotFoundError when no GoodAchievement ID was found.
func (gaq *GoodAchievementQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = gaq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{goodachievement.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gaq *GoodAchievementQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := gaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GoodAchievement entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GoodAchievement entity is found.
// Returns a *NotFoundError when no GoodAchievement entities are found.
func (gaq *GoodAchievementQuery) Only(ctx context.Context) (*GoodAchievement, error) {
	nodes, err := gaq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{goodachievement.Label}
	default:
		return nil, &NotSingularError{goodachievement.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gaq *GoodAchievementQuery) OnlyX(ctx context.Context) *GoodAchievement {
	node, err := gaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GoodAchievement ID in the query.
// Returns a *NotSingularError when more than one GoodAchievement ID is found.
// Returns a *NotFoundError when no entities are found.
func (gaq *GoodAchievementQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = gaq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{goodachievement.Label}
	default:
		err = &NotSingularError{goodachievement.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gaq *GoodAchievementQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := gaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GoodAchievements.
func (gaq *GoodAchievementQuery) All(ctx context.Context) ([]*GoodAchievement, error) {
	if err := gaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return gaq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (gaq *GoodAchievementQuery) AllX(ctx context.Context) []*GoodAchievement {
	nodes, err := gaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GoodAchievement IDs.
func (gaq *GoodAchievementQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := gaq.Select(goodachievement.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gaq *GoodAchievementQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := gaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gaq *GoodAchievementQuery) Count(ctx context.Context) (int, error) {
	if err := gaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return gaq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (gaq *GoodAchievementQuery) CountX(ctx context.Context) int {
	count, err := gaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gaq *GoodAchievementQuery) Exist(ctx context.Context) (bool, error) {
	if err := gaq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return gaq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (gaq *GoodAchievementQuery) ExistX(ctx context.Context) bool {
	exist, err := gaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GoodAchievementQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gaq *GoodAchievementQuery) Clone() *GoodAchievementQuery {
	if gaq == nil {
		return nil
	}
	return &GoodAchievementQuery{
		config:     gaq.config,
		limit:      gaq.limit,
		offset:     gaq.offset,
		order:      append([]OrderFunc{}, gaq.order...),
		predicates: append([]predicate.GoodAchievement{}, gaq.predicates...),
		// clone intermediate query.
		sql:    gaq.sql.Clone(),
		path:   gaq.path,
		unique: gaq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GoodAchievement.Query().
//		GroupBy(goodachievement.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (gaq *GoodAchievementQuery) GroupBy(field string, fields ...string) *GoodAchievementGroupBy {
	grbuild := &GoodAchievementGroupBy{config: gaq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := gaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return gaq.sqlQuery(ctx), nil
	}
	grbuild.label = goodachievement.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.GoodAchievement.Query().
//		Select(goodachievement.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (gaq *GoodAchievementQuery) Select(fields ...string) *GoodAchievementSelect {
	gaq.fields = append(gaq.fields, fields...)
	selbuild := &GoodAchievementSelect{GoodAchievementQuery: gaq}
	selbuild.label = goodachievement.Label
	selbuild.flds, selbuild.scan = &gaq.fields, selbuild.Scan
	return selbuild
}

func (gaq *GoodAchievementQuery) prepareQuery(ctx context.Context) error {
	for _, f := range gaq.fields {
		if !goodachievement.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gaq.path != nil {
		prev, err := gaq.path(ctx)
		if err != nil {
			return err
		}
		gaq.sql = prev
	}
	if goodachievement.Policy == nil {
		return errors.New("ent: uninitialized goodachievement.Policy (forgotten import ent/runtime?)")
	}
	if err := goodachievement.Policy.EvalQuery(ctx, gaq); err != nil {
		return err
	}
	return nil
}

func (gaq *GoodAchievementQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GoodAchievement, error) {
	var (
		nodes = []*GoodAchievement{}
		_spec = gaq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*GoodAchievement).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &GoodAchievement{config: gaq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(gaq.modifiers) > 0 {
		_spec.Modifiers = gaq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (gaq *GoodAchievementQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gaq.querySpec()
	if len(gaq.modifiers) > 0 {
		_spec.Modifiers = gaq.modifiers
	}
	_spec.Node.Columns = gaq.fields
	if len(gaq.fields) > 0 {
		_spec.Unique = gaq.unique != nil && *gaq.unique
	}
	return sqlgraph.CountNodes(ctx, gaq.driver, _spec)
}

func (gaq *GoodAchievementQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := gaq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (gaq *GoodAchievementQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   goodachievement.Table,
			Columns: goodachievement.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: goodachievement.FieldID,
			},
		},
		From:   gaq.sql,
		Unique: true,
	}
	if unique := gaq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := gaq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goodachievement.FieldID)
		for i := range fields {
			if fields[i] != goodachievement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gaq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gaq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gaq *GoodAchievementQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gaq.driver.Dialect())
	t1 := builder.Table(goodachievement.Table)
	columns := gaq.fields
	if len(columns) == 0 {
		columns = goodachievement.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gaq.sql != nil {
		selector = gaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gaq.unique != nil && *gaq.unique {
		selector.Distinct()
	}
	for _, m := range gaq.modifiers {
		m(selector)
	}
	for _, p := range gaq.predicates {
		p(selector)
	}
	for _, p := range gaq.order {
		p(selector)
	}
	if offset := gaq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gaq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (gaq *GoodAchievementQuery) ForUpdate(opts ...sql.LockOption) *GoodAchievementQuery {
	if gaq.driver.Dialect() == dialect.Postgres {
		gaq.Unique(false)
	}
	gaq.modifiers = append(gaq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return gaq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (gaq *GoodAchievementQuery) ForShare(opts ...sql.LockOption) *GoodAchievementQuery {
	if gaq.driver.Dialect() == dialect.Postgres {
		gaq.Unique(false)
	}
	gaq.modifiers = append(gaq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return gaq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (gaq *GoodAchievementQuery) Modify(modifiers ...func(s *sql.Selector)) *GoodAchievementSelect {
	gaq.modifiers = append(gaq.modifiers, modifiers...)
	return gaq.Select()
}

// GoodAchievementGroupBy is the group-by builder for GoodAchievement entities.
type GoodAchievementGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gagb *GoodAchievementGroupBy) Aggregate(fns ...AggregateFunc) *GoodAchievementGroupBy {
	gagb.fns = append(gagb.fns, fns...)
	return gagb
}

// Scan applies the group-by query and scans the result into the given value.
func (gagb *GoodAchievementGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := gagb.path(ctx)
	if err != nil {
		return err
	}
	gagb.sql = query
	return gagb.sqlScan(ctx, v)
}

func (gagb *GoodAchievementGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range gagb.fields {
		if !goodachievement.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := gagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (gagb *GoodAchievementGroupBy) sqlQuery() *sql.Selector {
	selector := gagb.sql.Select()
	aggregation := make([]string, 0, len(gagb.fns))
	for _, fn := range gagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(gagb.fields)+len(gagb.fns))
		for _, f := range gagb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(gagb.fields...)...)
}

// GoodAchievementSelect is the builder for selecting fields of GoodAchievement entities.
type GoodAchievementSelect struct {
	*GoodAchievementQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (gas *GoodAchievementSelect) Scan(ctx context.Context, v interface{}) error {
	if err := gas.prepareQuery(ctx); err != nil {
		return err
	}
	gas.sql = gas.GoodAchievementQuery.sqlQuery(ctx)
	return gas.sqlScan(ctx, v)
}

func (gas *GoodAchievementSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := gas.sql.Query()
	if err := gas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (gas *GoodAchievementSelect) Modify(modifiers ...func(s *sql.Selector)) *GoodAchievementSelect {
	gas.modifiers = append(gas.modifiers, modifiers...)
	return gas
}
