// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/inspire-middleware/pkg/db/ent/goodcoinachievement"
	"github.com/NpoolPlatform/inspire-middleware/pkg/db/ent/predicate"
)

// GoodCoinAchievementDelete is the builder for deleting a GoodCoinAchievement entity.
type GoodCoinAchievementDelete struct {
	config
	hooks    []Hook
	mutation *GoodCoinAchievementMutation
}

// Where appends a list predicates to the GoodCoinAchievementDelete builder.
func (gcad *GoodCoinAchievementDelete) Where(ps ...predicate.GoodCoinAchievement) *GoodCoinAchievementDelete {
	gcad.mutation.Where(ps...)
	return gcad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gcad *GoodCoinAchievementDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gcad.hooks) == 0 {
		affected, err = gcad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GoodCoinAchievementMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gcad.mutation = mutation
			affected, err = gcad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gcad.hooks) - 1; i >= 0; i-- {
			if gcad.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gcad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gcad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcad *GoodCoinAchievementDelete) ExecX(ctx context.Context) int {
	n, err := gcad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gcad *GoodCoinAchievementDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: goodcoinachievement.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: goodcoinachievement.FieldID,
			},
		},
	}
	if ps := gcad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gcad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// GoodCoinAchievementDeleteOne is the builder for deleting a single GoodCoinAchievement entity.
type GoodCoinAchievementDeleteOne struct {
	gcad *GoodCoinAchievementDelete
}

// Exec executes the deletion query.
func (gcado *GoodCoinAchievementDeleteOne) Exec(ctx context.Context) error {
	n, err := gcado.gcad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{goodcoinachievement.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gcado *GoodCoinAchievementDeleteOne) ExecX(ctx context.Context) {
	gcado.gcad.ExecX(ctx)
}
