// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/inspire-middleware/pkg/db/ent/orderpaymentstatement"
	"github.com/NpoolPlatform/inspire-middleware/pkg/db/ent/predicate"
)

// OrderPaymentStatementDelete is the builder for deleting a OrderPaymentStatement entity.
type OrderPaymentStatementDelete struct {
	config
	hooks    []Hook
	mutation *OrderPaymentStatementMutation
}

// Where appends a list predicates to the OrderPaymentStatementDelete builder.
func (opsd *OrderPaymentStatementDelete) Where(ps ...predicate.OrderPaymentStatement) *OrderPaymentStatementDelete {
	opsd.mutation.Where(ps...)
	return opsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (opsd *OrderPaymentStatementDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(opsd.hooks) == 0 {
		affected, err = opsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrderPaymentStatementMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			opsd.mutation = mutation
			affected, err = opsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(opsd.hooks) - 1; i >= 0; i-- {
			if opsd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = opsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, opsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (opsd *OrderPaymentStatementDelete) ExecX(ctx context.Context) int {
	n, err := opsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (opsd *OrderPaymentStatementDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: orderpaymentstatement.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: orderpaymentstatement.FieldID,
			},
		},
	}
	if ps := opsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, opsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// OrderPaymentStatementDeleteOne is the builder for deleting a single OrderPaymentStatement entity.
type OrderPaymentStatementDeleteOne struct {
	opsd *OrderPaymentStatementDelete
}

// Exec executes the deletion query.
func (opsdo *OrderPaymentStatementDeleteOne) Exec(ctx context.Context) error {
	n, err := opsdo.opsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orderpaymentstatement.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (opsdo *OrderPaymentStatementDeleteOne) ExecX(ctx context.Context) {
	opsdo.opsd.ExecX(ctx)
}
