// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Achievement is the predicate function for achievement builders.
type Achievement func(*sql.Selector)

// AchievementUser is the predicate function for achievementuser builders.
type AchievementUser func(*sql.Selector)

// AppCommissionConfig is the predicate function for appcommissionconfig builders.
type AppCommissionConfig func(*sql.Selector)

// AppConfig is the predicate function for appconfig builders.
type AppConfig func(*sql.Selector)

// AppGoodCommissionConfig is the predicate function for appgoodcommissionconfig builders.
type AppGoodCommissionConfig func(*sql.Selector)

// AppGoodScope is the predicate function for appgoodscope builders.
type AppGoodScope func(*sql.Selector)

// CashControl is the predicate function for cashcontrol builders.
type CashControl func(*sql.Selector)

// Commission is the predicate function for commission builders.
type Commission func(*sql.Selector)

// Coupon is the predicate function for coupon builders.
type Coupon func(*sql.Selector)

// CouponAllocated is the predicate function for couponallocated builders.
type CouponAllocated func(*sql.Selector)

// CouponScope is the predicate function for couponscope builders.
type CouponScope func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// InvitationCode is the predicate function for invitationcode builders.
type InvitationCode func(*sql.Selector)

// PubsubMessage is the predicate function for pubsubmessage builders.
type PubsubMessage func(*sql.Selector)

// Registration is the predicate function for registration builders.
type Registration func(*sql.Selector)

// Statement is the predicate function for statement builders.
type Statement func(*sql.Selector)
